MUNICIPIOS_BACIA = {
    "Rio do Sul",
    "Agronômica",
    "Aurora",
    "Lontras",
    "Laurentino",
    "Rio do Oeste",
    "Trombudo Central",
    "Agrolândia",
    "Atalanta",
    "Petrolândia",
    "Ituporanga",
    "Chapadão do Lageado",
    "Imbuia",
    "Vidal Ramos",
    "Leoberto Leal",
    "José Boiteux",
    "Taió",
    "Salete",
    "Rio do Campo",
    "Santa Terezinha",
    "Mirim Doce",
    "Pouso Redondo",
    "Benedito Novo",
}

MUNICIPIOS_BACIA_IBGE = [
    {"codigo_ibge": "4214805", "municipio": "Rio do Sul"},
    {"codigo_ibge": "4200309", "municipio": "Agronômica"},
    {"codigo_ibge": "4201901", "municipio": "Aurora"},
    {"codigo_ibge": "4209904", "municipio": "Lontras"},
    {"codigo_ibge": "4209508", "municipio": "Laurentino"},
    {"codigo_ibge": "4214607", "municipio": "Rio do Oeste"},
    {"codigo_ibge": "4218608", "municipio": "Trombudo Central"},
    {"codigo_ibge": "4200200", "municipio": "Agrolândia"},
    {"codigo_ibge": "4201802", "municipio": "Atalanta"},
    {"codigo_ibge": "4212700", "municipio": "Petrolândia"},
    {"codigo_ibge": "4208500", "municipio": "Ituporanga"},
    {"codigo_ibge": "4204194", "municipio": "Chapadão do Lageado"},
    {"codigo_ibge": "4207403", "municipio": "Imbuia"},
    {"codigo_ibge": "4219200", "municipio": "Vidal Ramos"},
    {"codigo_ibge": "4209805", "municipio": "Leoberto Leal"},
    {"codigo_ibge": "4209151", "municipio": "José Boiteux"},
    {"codigo_ibge": "4217808", "municipio": "Taió"},
    {"codigo_ibge": "4215307", "municipio": "Salete"},
    {"codigo_ibge": "4214508", "municipio": "Rio do Campo"},
    {"codigo_ibge": "4215901", "municipio": "Santa Terezinha"},
    {"codigo_ibge": "4210852", "municipio": "Mirim Doce"},
    {"codigo_ibge": "4213708", "municipio": "Pouso Redondo"},
    {"codigo_ibge": "4202206", "municipio": "Benedito Novo"},
]